name: Ivan Nava
favicon: null
layout_spectrum: 0.24779
typography_spectrum: 0.38759357179515064
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000006'
    - '#ffffff'
    - '#a7c9e0'
    - '#007885'
    - '#c20713'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.42522459337487817
purpose: []
