name: Ivan Nava
favicon: null
layout_spectrum: 0
typography_spectrum: 0.74688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#09030f'
    - '#474363'
    - '#7e7ca1'
    - '#ed798c'
    - '#ffe6d4'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
